// lib/data.js

export const sheetData = [
  { branch: 'ATC', gender: 'Female', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'TR' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'TR' },
  { branch: 'GS (Electrical)', gender: 'Female', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'TR' },
  { branch: 'GS (Electrical)', gender: 'Female', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Female', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Female', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Female', status: 'TR' },
  { branch: 'GS (Electrical)', gender: 'Female', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'TR' },
  { branch: 'GS (Electrical)', gender: 'Female', status: 'TR' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Female', status: 'TR' },
  { branch: 'GS (Electrical)', gender: 'Female', status: 'TR' },
  { branch: 'GS (Electrical)', gender: 'Female', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Female', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'TR' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'TR' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'TR' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'TR' },
  { branch: 'GS (Electrical)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'TR' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'TR' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'TR' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'TR' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'TR' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'TR' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Engineer)', gender: 'Male', status: 'TR' },
  { branch: 'GS (Hydro)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Hydro)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (Hydro)', gender: 'Female', status: 'FIT' },
  { branch: 'GS (Hydro)', gender: 'Female', status: 'FIT' },
  { branch: 'GS (Hydro)', gender: 'Female', status: 'FIT' },
  { branch: 'GS (Hydro)', gender: 'Female', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Female', status: 'TR' },
  { branch: 'GS (X)', gender: 'Female', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Female', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Female', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Male', status: 'TR' },
  { branch: 'GS (X)', gender: 'Male', status: 'TR' },
  { branch: 'GS (X)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Female', status: 'TR' },
  { branch: 'GS (X)', gender: 'Female', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Female', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Female', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Male', status: 'TR' },
  { branch: 'GS (X)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Male', status: 'TR' },
  { branch: 'GS (X)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Male', status: 'TR' },
  { branch: 'GS (X)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Male', status: 'TR' },
  { branch: 'GS (X)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Male', status: 'FIT' },
  { branch: 'GS (X)', gender: 'Male', status: 'FIT' },
  { branch: 'Logistics', gender: 'Male', status: 'PENDING' },
  { branch: 'Logistics', gender: 'Male', status: 'PENDING' },
  { branch: 'Logistics', gender: 'Male', status: 'PENDING' },
  { branch: 'NAOO', gender: 'Male', status: 'TR' },
  { branch: 'NAOO', gender: 'Male', status: 'FIT' },
  { branch: 'NAOO', gender: 'Female', status: 'FIT' },
  { branch: 'NAOO', gender: 'Female', status: 'TR' },
  { branch: 'NAOO', gender: 'Male', status: 'TR' },
  { branch: 'NAOO', gender: 'Male', status: 'TR' },
  { branch: 'NAOO', gender: 'Male', status: 'TR' },
  { branch: 'NAOO', gender: 'Female', status: 'TR' },
  { branch: 'NAOO', gender: 'Male', status: 'TR' },
  { branch: 'Naval Constructor', gender: 'Male', status: 'FIT' },
  { branch: 'Naval Constructor', gender: 'Male', status: 'FIT' },
  { branch: 'Naval Constructor', gender: 'Male', status: 'FIT' },
  { branch: 'Naval Constructor', gender: 'Male', status: 'TR' },
  { branch: 'Naval Constructor', gender: 'Male', status: 'FIT' },
  { branch: 'Naval Constructor', gender: 'Male', status: 'FIT' },
  { branch: 'Naval Constructor', gender: 'Male', status: 'FIT' },
  { branch: 'Naval Constructor', gender: 'Male', status: 'FIT' },
  { branch: 'Naval Constructor', gender: 'Male', status: 'FIT' },
  { branch: 'Naval Constructor', gender: 'Male', status: 'TR' },
  { branch: 'Naval Constructor', gender: 'Male', status: 'FIT' },
  { branch: 'Naval Constructor', gender: 'Male', status: 'FIT' },
  { branch: 'Naval Constructor', gender: 'Male', status: 'TR' },
  { branch: 'Naval Constructor', gender: 'Male', status: 'TR' },
  { branch: 'Naval Constructor', gender: 'Female', status: 'FIT' },
  { branch: 'Naval Constructor', gender: 'Female', status: 'FIT' },
  { branch: 'Naval Constructor', gender: 'Female', status: 'TR' },
  { branch: 'Naval Constructor', gender: 'Female', status: 'FIT' },
  { branch: 'Naval Constructor', gender: 'Female', status: 'FIT' },
  { branch: 'Naval Constructor', gender: 'Female', status: 'FIT' },
  { branch: 'Naval Constructor', gender: 'Female', status: 'TR' },
  { branch: 'Naval Constructor', gender: 'Male', status: 'FIT' },
  { branch: 'Pilot', gender: 'Male', status: 'TR' },
  { branch: 'Pilot', gender: 'Male', status: 'TR' },
  { branch: 'Pilot', gender: 'Female', status: 'FIT' },
  { branch: 'Pilot', gender: 'Male', status: 'TR' },
  { branch: 'Pilot', gender: 'Male', status: 'TR' },
  { branch: 'Pilot', gender: 'Male', status: 'TR' },
  { branch: 'Pilot', gender: 'Male', status: 'FIT' },
  { branch: 'Pilot', gender: 'Male', status: 'TR' },
  { branch: 'Pilot', gender: 'Male', status: 'FIT' },
  { branch: 'Pilot', gender: 'Male', status: 'FIT' },
  { branch: 'Pilot', gender: 'Male', status: 'FIT' },
];

export const processData = () => {
  const branchData = {};
  sheetData.forEach(({ branch, gender, status }) => {
    if (!branchData[branch]) {
      branchData[branch] = {
        male_fit: 0,
        female_fit: 0,
        male_unfit: 0,
        female_unfit: 0,
      };
    }
    if (gender === 'Male') {
      if (status === 'FIT') {
        branchData[branch].male_fit++;
      } else {
        branchData[branch].male_unfit++;
      }
    } else if (gender === 'Female') {
      if (status === 'FIT') {
        branchData[branch].female_fit++;
      } else {
        branchData[branch].female_unfit++;
      }
    }
  });
  return Object.keys(branchData).map(branch => ({
    name: branch,
    ...branchData[branch],
  }));
};